### ISSUE TITLE
getNewLineNo() and "No newline at end of file"

### ISSUE THREAD

**Issue by dmrsol** [ptlis/diff-parser#6]
Hello! Git generated diff:
```
diff --git a/file.php b/file.php
index 272b2e4..7a9961d 100644
--- a/file.php
+++ b/file.php
@@ -1,3 +1,6 @@
 first line
 second line
-third line
\ No newline at end of file
+third line
+fourth line
+
+some other line
```

Current file content:
```
first line
second line
third line
fourth line

some other line

```

Display line numbers:
```php
use ptlis\DiffParser\Parser;

$parser = new Parser();

$changeset = $parser->parseFile('C:/server/projects/dev/master-protect/git-line.diff', Parser::VCS_GIT);
$files = $changeset->getFiles();

foreach ($files as $file) {
    $hunks = $file->getHunks();
    foreach ($hunks as $hunk) {
        $lines = $hunk->getLines();

        foreach ($lines as $line) {
            echo 'getOriginalLineNo: ' . $line->getOriginalLineNo() . ' getNewLineNo: ' . $line->getNewLineNo() . ' ' . $line->getContent() . "\n";
        }
    }
}
```

Output:
```
getOriginalLineNo: 1 getNewLineNo: 1 first line
getOriginalLineNo: 2 getNewLineNo: 2 second line
getOriginalLineNo: 3 getNewLineNo: -1 third line
getOriginalLineNo: 4 getNewLineNo: 3  No newline at end of file
getOriginalLineNo: -1 getNewLineNo: 4 third line
getOriginalLineNo: -1 getNewLineNo: 5 fourth line
getOriginalLineNo: -1 getNewLineNo: 6
getOriginalLineNo: -1 getNewLineNo: 7 some other line
```

Why getNewLineNo() gets +1 for line number after "No newline at end of file"? I expected that "third line" is 3, "fourth line" is 4 and "some other line" is 6. Is this a mistake or do I understand something wrong?

**Comment by ptlis** [comment]
Hi dmrsol, the simple answer is that this is an side-effect of the file format for diff files that git uses patches.

The complete answer is a little more complex:

Git includes this line as there is a long-running convention that files will always be terminated with a newline, and most (if not all) Linux terminal commands assume that this is the case. The rationale for this is to make working with files more convenient at the terminal. An example of this in action can be seen when you 'cat' a file that doesn't include a newline - your cursor position will be left inline with the end of the file & not aligned left on a fresh line.

As a diff is a 'line-by-line' algorithm it doesn't encode newlines explicitly - in the average case each line of a diff can be assumed to be terminated with a newline.

The consequence of the interaction between these conventions / rules is that diff needs to explicitly encode the absence of a newline in a 'phantom line' - a line that doens't exist in the file but must be tracked to allow proper merging from a patch file.

The reason that I chose to use "the final line number + 1" as the line number when represented in memory is that at the time of writing I couldn't think of any non-sucky way to represent this information. There were two obvious choices to me at the time:  
* Re-using the final line number (as you suggested) would lead to strangeness in tools that consumed these data-structures that rightfully assume that line numbers *MUST* be unique. 
* Creating a 'phantom line' meant that the generated data-structure was 'lying' about the structure of the diff'd file, but was in-line with the textual representation used in patch files.

Obviously I chose the latter at that time, but on reviewing that decision in light of this question I don't think that either of these options is the right way of doing things. I'm going to work up a change so that whether there is a newline or not at the end of a hunk is encoded in the hunk data-structure. This will allow me to eliminate the phantom  "No newline at end of file" line from the data-structure but correctly track that data when re-encoding back to the textual representation.

**Comment by dmrsol** [comment]
It would be great! Thanks for the detailed answer

**Comment by ptlis** [comment]
I've just merged a branch that should fix this issue - you should be able to confirm this by pulling from the master branch.

I'm planning on making a 0.7.0 release fairly shortly so that a stable release containing these fixes can be used.

**Comment by dmrsol** [comment]
Everything is ok now. Thank you
